src/apis/member/memberApi.ts
src/hooks/mutations/usePatchProfile.ts
src/hooks/useDebounce.ts
src/pages/my/edit.tsx

close #40 
- 닉네임 수정 커스텀 훅을 생성했습니다.
- debounce를 통해 타이핑이 끝나고 0.4초 후 닉네임 중복확인 api가 동작합니다.
- 닉네임 수정 인풋의 패턴을 추가하여 패턴에 해당하지 않으면 버튼이 disabled 됩니다.
- 닉네임의 패턴도 일치하고 중복되지 않은 경우에만 버튼이 활성화됩니다.
https://user-images.githubusercontent.com/79186378/230785956-40f2f9fb-28f6-46ea-89b2-773ae2777f6f.mov

feat: #40/ 닉네임 수정 구현

---

src/components/home/Category.tsx
src/styles/globals.css

카테고리 버그 수정
- close #37 
- global.css에 스타일 override 하여 width값 해결했습니다.
- 카테고리 3번째 인덱스(포토이즘)을 클릭했을 때 자동으로 스와이프 되게끔 핸들러를 작성했습니다.
https://user-images.githubusercontent.com/48711263/230840879-8841d54c-f043-4988-969f-af6fe0a20c73.mov

fix: #37/카테고리 버그 수정

---

src/apis/instance.ts
src/components/common/Map.tsx
src/pages/_app.tsx
src/pages/my/index.tsx
src/utils/getImgSrc.ts

close #55 
- 로그인이 필요한 페이지를 나누고, 해당 페이지 접근 시 모달을 띄우도록 구현했습니다.
- Map 컴포넌트 내에서 사용하던 이미지 관련 함수를 util 함수로 뺐습니다.
- 해당 pr 머지 후 배포 진행하도록 하겠습니다.
https://user-images.githubusercontent.com/79186378/232306927-ca8ced11-324e-4f39-a912-6f240dfda387.mov

feat: #55/ 비로그인 유저 로직 구현

---

src/apis/favorite/favoriteApi.ts
src/components/common/NavBar.tsx
src/components/common/ToastMessage.tsx
src/components/home/ShopModal.tsx
src/components/navbar/SearchList.tsx
src/components/navbar/SearchResult.tsx
src/components/wish/FavoriteButton.tsx
src/components/wish/WishItem.tsx
src/hooks/mutations/useDeleteFavorite.ts
src/hooks/mutations/usePostFavorite.ts
src/hooks/queries/useGetFavorite.ts
src/hooks/queries/useGetReview.ts
src/hooks/queries/useGetShop.ts
src/pages/_app.tsx
src/pages/shopDetail/index.tsx
src/pages/wish/index.tsx

비로그인 시 상세페이지 접근 불가능한 현상 해결
- close #71 
- #73  
- 찜 페이지에서는 컴포넌트를 활용하지 않고 찜 버튼을 사용하게끔 수정하였습니다.
- 상세페이지에서는 favorite의 boolean 값을 보내주어 처리하도록 수정하였습니다.
- 현재 DB에 네컷사진 브랜드가 아닌 데이터는 삭제되었기 때문에 select 옵션으로 필터링 하는 것을 제거했습니다.
- `ShopModal` 컴포넌트에서 찜 추가/삭제 버튼을 눌러도 렌더링이 될 수가 없기 때문에 내부에 state를 생성해 할당하였습니다.

fix: #71/비로그인 시 상세페이지 접근 불가능한 현상 해결

---

src/components/home/ShopModal.tsx
src/hooks/mutations/useDeleteFavorite.ts
src/hooks/mutations/usePostFavorite.ts
src/pages/home/index.tsx

마커 모달 찜 버그 수정
- close #76 
현재 찜 추가/삭제 시 마커 클릭 상태가 해제되는 현상이 있습니다. 각 마커에 대한 찜 여부를 실시간으로 반영하려면 `shopInfo`가 수정될 수 밖에 없어서 기술적으로 현재 해결 방법을 찾지 못한 상태입니다. 추후에 해결 방안을 고민해보도록 하겠습니다.

fix: #76/ShopModal 찜 버그 수정

---

src/components/common/Scripts.tsx
src/components/home/ShopModal.tsx
src/components/wish/FavoriteButton.tsx
src/components/wish/WishItem.tsx
src/hooks/mutations/useDeleteFavorite.ts
src/hooks/mutations/usePostFavorite.ts
src/hooks/queries/useGetShop.ts
src/pages/home/index.tsx
src/utils/getImgSrc.ts

close #84 
- shopModal 컴포넌트로 전달하는 해당 지점 id를 통해 useGetShopDetail을 커스텀 훅을 사용합니다.
- 해당 커스텀 훅을 통해 받은 지점 데이터의 favorite을 가지고 찜, 찜 취소를 합니다.
- 찜, 찜 취소후에는 캐시 무효화를 합니다.
- 찜이 사용되는 페이지와 해당 페이지에서 무효화 할 캐시가 달라 path에 따른 낙관적 업데이트를 구현했습니다.
- home 페이지에서 로그인 상태를 확인하고 shopModal에서 찜버튼을 누르면 비로그인 시 모달을 보여줍니다.
- 지점 상세 페이지에서 지점 종류에 따라 마커를 보여주도록 util함수를 사용했습니다.
https://user-images.githubusercontent.com/79186378/233841568-5cf1b722-5ee7-481b-b9e8-95975c66fce9.mov
https://user-images.githubusercontent.com/79186378/233841549-ab29a74d-2b15-44df-abcb-a4ed3549199c.mov

feat: #84/ 찜 삭제 낙관적 업데이트 구현 & shopModal 찜 버그 수정

---

src/components/home/ShopModal.tsx
src/components/navbar/SearchResult.tsx
src/pages/home/index.tsx
src/pages/shopDetail/index.tsx

close #86 
- 지점 상세페이지 새로고침 시 지도 불러오지 못하는 현상을 수정했습니다.
- 홈페이지에서 ShopModal 컴포넌트 내 찜, 찜 취소 시 찜 수 반영되지 않는 현상 수정했습니다.
- 검색 결과 클릭 시 지점 상세 페이지로 이동하도록 수정했습니다.

fix: #86/ 지점 상세페이지 새로고침 시 지도 불러오지 못하는 현상 수정

---

src/apis/favorite/favorite.d.ts
src/apis/favorite/favoriteApi.ts
src/apis/shop/shop.d.ts
src/apis/shop/shopApi.ts
src/components/common/Map.tsx
src/components/common/NavBar.tsx
src/hooks/queries/useGetFavorite.ts
src/hooks/queries/useGetShop.ts
src/pages/home/index.tsx
src/pages/wish/index.tsx

close #98 
- 깃북에 반영된 대로 api 타입 수정사항 반영했습니다.
- 추가적인 파라미터 전달하여 지점과 떨어진 거리를 현재 위치 기반으로 받도록 합니다.
- 찜 목록 불러오기 api에 임의로 전달하던 위도, 경도를 geolocation API 기반으로 불러온 현재위치를 전달합니다.
- 위치가 자주 사용됨에 따라 geolocation API의 반복적인 사용으로 추후에 현재위치는 클라이언트 state로 관리하면 좋을것같습니다.
- 지도 지역명은 pull 하시고 작업하시면 될것같습니다.

refactor: #98/ api 타입 수정사항 반영

---

src/components/common/NavBar.tsx

지도 로딩 중일 때 지도지역명 안 보이게 수정
- close #104
저번 PR에 같이 올렸어야 했던 사항이지만, 지도 로딩 중일 때 기본 중심 좌표인 제주특별자치도 ~~ 로 나와서 이를 `location?.lat !== 33.450701 && location?.lng !== 126.570667`일 때 지도지역명이 안 보이게 처리하였습니다.

refactor: #104/지도 로딩 중일 때 지도지역명 안 보이게 수정

---

next.config.js
src/apis/instance.ts
src/components/common/LocationMap.tsx
src/components/home/Category.tsx
src/components/location/ShopItem.tsx
src/hooks/queries/useGetShop.ts
src/pages/home/index.tsx
src/pages/location/index.tsx

close #92 
- 내 주변 페이지 구현완료했습니다.
- 기존 카테고리에서 브랜드 선택시 브랜드 교체마다 api 재요청을 통해 지점 값을 교체하여 렌더링했는데, 추가적인 api 재요청없이 필터링통해서 렌더링하도록 수정했습니다.
- 외부이미지 받아오기 위해 next.config.js 파일에 도메인을 추가했습니다.

feat: #92/ 내주변 페이지 구현

---

src/components/home/ShopModal.tsx
src/components/layout/Layout.tsx
src/components/location/ShopItem.tsx
src/components/wish/FavoriteButton.tsx
src/pages/_app.tsx
src/pages/home/index.tsx
src/pages/location/index.tsx
src/pages/shopDetail/index.tsx
src/recoil/modalAtom.ts
src/recoil/userAtom.ts
src/utils/token.ts

close #136 
- 유저 로그인 상태와 모달 상태를 recoil로 전역으로 관리하도록 수정했습니다.
- 로그인 상태가 아닐때, 로그인 모달창을 띄우는 관련 로직 또한 다수 존재하여, `Layout` 컴포넌트 내에서 일괄적으로 모달을 관리하도록 수정했습니다.
- 각 페이지에서는 recoil의 `useSetRecoilState` 훅을 통해 모달의 상태를 조작합니다.
- pagePerLayout을 사용하지 않아 `_app.tsx`에서 getLayout을 제거했습니다.

refactor: #136/ 유저 로그인 상태, 모달 상태 전역 관리

---

src/components/navbar/Search.tsx
src/components/navbar/TextHighlighted.tsx
src/pages/_app.tsx

검색어 value 없을 때 초기 상태로 설정
- resolve #141
- 검색어 하이라이팅 공백 문제가 추가적으로 발생함을 발견해서 해결했습니다. 
`useGetShopsByKeword` 커스텀 훅 내부에 useEffect 사용하지 않아도 지속적인 호출은 없어보이네요. 좋지 않은 방법이여도 임시적으로 제어하기 위해 강제적으로 사용했었는데 다행이네요👍

fix: #141/검색어 value 없을 때 초기 상태로 설정

---

src/hooks/mutations/useDeleteReview.ts
src/hooks/mutations/usePostReview.ts
src/pages/my/reviews/edit.tsx
src/pages/my/reviews/index.tsx
src/pages/wish/index.tsx

close #144 
- 리뷰 수정 작업 시 콘텐츠가 없는 경우 버튼이 비활성화 되도록 수정했습니다.
- 리뷰 등록, 삭제 시 관련 쿼리를 무효화하도록 수정했습니다.
- 찜목록, 리뷰 작성 목록이 없을 때 보여주는 뷰의 높이를 수정했습니다.
- 리뷰 수정 페이지에 접근 후 해당 NavBar의 뒤로가기 버튼을 누르면 다시 리뷰 수정 페이지로 이동하는 문제가 있어, 리뷰 수정 페이지로 이동시  router.push가 아닌 router.replace로 처리하여 히스토리 스택에 리뷰 수정 페이지를 추가하지 않도록 수정했습니다.

refactor: #144/ review 관련 사항 수정

---

src/pages/auth/kakao.tsx

로그인 성공 후 라우터 히스토리 스택 안 쌓이게 수정
- close #152 
- 이제 로그인 성공 후 뒤로가기를 해도 로그인 페이지로 이동하지 않습니다.
- 로그인 없이 이용하기 및 로그인 모달은 replace로 변경하지 않고 유지했습니다.

refactor: #152/로그인 성공 후 히스토리 스택 안 쌓이게 수정

---

src/pages/auth/login.tsx

close #160 
- 로그인 없이 이용 모달에서 로그인하기 버튼 클릭시 이동하는 redirect uri를 개발서버와 배포서버로 구분했습니다.

fix : #160/ 배포서버와 개발서버 redirect-uri 구분

---

src/components/common/Button.tsx
src/hooks/queries/useGetReview.ts
src/pages/my/index.tsx
src/pages/my/reviews/edit.tsx
src/pages/my/reviews/index.tsx
src/pages/my/setting.tsx
src/pages/shopDetail/index.tsx
src/pages/shopDetail/review.tsx

close #155
close #154 
- 지점 상세 페이지에 메뉴 컴포넌트를 추가했습니다.
- 지점 상세페이지에 접근시 지점 모든 리뷰를 가져오도록 되어있었는데, 추가 리뷰 버튼을 누르면 모든 리뷰를 가져오게하여 불필요한 api 호출을 수정했습니다.
- 후기 -> 리뷰로 명칭을 통일했습니다.

refactor: #155/ 지점 상세 페이지 리팩토링 & 리뷰로 명칭 통일

---

src/components/common/LocationMap.tsx
src/components/common/Map.tsx
src/pages/shopDetail/index.tsx

close #157 
- 홈, 내주변 페이지에서 현재 위치 가져오기 전 본사 위치를 recoil 상태로 관리하지 않도록 수정했습니다.

refactor: #157/ 위치 이슈 수정

---

src/components/common/NavBar.tsx
src/pages/home/index.tsx
src/pages/location/index.tsx

close #170  close #173 
- 지점 모달이 화면에 있는경우 검색 시 기존 모달이 유지되는 현상을 수정했습니다.
- 검색 결과 바탕으로 필터링 시 기존 위치 지점들이 필터링되는 현상을 수정했습니다.
- 기존 NavBar에서 본사 위치일 때 위치주소가 나타나지 않게끔 했던 부분을, 본사 위치를 setState 하지 않도록 로직을 수정함에 따라 제거했습니다.

fix: #170/#173/ 검색 후 기존 모달 유지 & 검색 결과 필터링

---

src/apis/review/review.d.ts
src/apis/shop/shop.d.ts
src/apis/title/title.d.ts
src/apis/title/titleApi.ts
src/components/common/ReviewItem.tsx
src/components/home/ShopModal.tsx
src/components/location/ShopItem.tsx
src/components/title/ShopTitle.tsx
src/components/title/TitleBadge.tsx
src/components/title/TitleInfo.tsx
src/components/title/TitleModal.tsx
src/hooks/mutations/usePatchTitle.ts
src/pages/my/index.tsx
src/pages/my/titles.tsx
src/pages/shopDetail/index.tsx

대표칭호 컴포넌트 작성 및 적용
-  close #179
- close #182 
- 대표 칭호 컴포넌트 (TitleBadge)를 작성해서 필요한 페이지에 적용했습니다.
- 자잘한 변동사항들이 많아서 TitleBadge, my/index.tsx, ReviewItem 위주로 보시면 될 것 같습니다.
- 지점 칭호(ShopTitle)을 common에서 title 폴더로 이동했습니다.
- 칭호 모달에 획득 방법 문구 추가했습니다.
<br />

feat: #179/대표칭호 컴포넌트 작성 및 적용

---

src/apis/shop/shop.d.ts
src/apis/shop/shopApi.ts
src/hooks/queries/useGetShop.ts
src/pages/home/index.tsx
src/pages/location/index.tsx
src/pages/shopDetail/index.tsx

close #183 
- 기존 반경 내 지점 조회 api 사용시 옵셔널 파라미터인 brand 값을 포함해 요청을 하고있었는데, 현재 로직 상 전체 조회 결과를 받아와 자체적으로 브랜드 state를 통해 필터링을 진행하고 있어서, 해당 파라미터를 삭제했습니다.
- place_url과 brand_id 응답 값에대한 수정사항 반영했습니다.
- 반경 조절 시 검색 결과 없을 때 텍스트를 수정했습니다.

fix: #183/ 내주변 페이지 특정 브랜드 필터링 상태에서 반경 조절시 전체 지점 받아오지 못하는 현상 수정

---

src/components/title/TitleModal.tsx
src/hooks/mutations/usePatchTitle.ts
src/pages/my/titles.tsx

- close #189 
- 획득하지 않은 칭호일 때 대표 칭호 설정 onClick 이벤트를 삭제했습니다.
- 대표 칭호 여부를 구분해서 테두리 굵기 및 색상에 변화를 주었습니다.
- 해당 수정사항에 따라 칭호 목록 중 대표 칭호 여부를 낙관적으로 업데이트 하도록 수정했습니다.

refactor: #189/칭호 수정사항 반영

---

src/components/common/Map.tsx
src/components/common/Modal.tsx
src/components/common/NavBar.tsx
src/components/home/ShopModal.tsx
src/components/location/ShopItem.tsx
src/components/my/SettingItem.tsx
src/components/my/SettingList.tsx
src/components/navbar/SearchList.tsx
src/components/navbar/SearchResult.tsx
src/components/wish/WishItem.tsx
src/pages/faq.tsx
src/pages/location/index.tsx
src/pages/my/index.tsx
src/pages/my/setting.tsx

- 내 주변 페이지의 지도를 정방향으로 수정했습니다.
- 애플리케이션 seo향상을 위해 특정 로직을 제외하고 next/Router 대신 next/Link를 사용하도록 수정했습니다.
- my 페이지에서 약관 관련 리스트를 삭제했습니다.

refactor: #191/ 내주변 페이지 지도 정방향 수정 및 next link 사용

---

src/components/common/Seo.tsx
src/components/common/SplashLogin.tsx
src/components/my/SettingItem.tsx
src/components/my/SettingList.tsx
src/pages/_app.tsx
src/pages/_document.tsx
src/pages/auth/login.tsx
src/pages/faq.tsx
src/pages/home/index.tsx
src/pages/location/index.tsx
src/pages/my/edit.tsx
src/pages/my/index.tsx
src/pages/my/reviews/edit.tsx
src/pages/my/reviews/index.tsx
src/pages/my/setting.tsx
src/pages/my/titles.tsx
src/pages/notice.tsx
src/pages/shopDetail/index.tsx
src/pages/shopDetail/review.tsx
src/pages/terms.tsx
src/pages/wish/index.tsx

close #193 
- `viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta` 메시지가 반복 출력되는 현상 수정을 위해 _document.tsx 파일 내에서 뷰포트 메타태그를 제거하고 공통적인 메타 태그를 추가했습니다.
- Seo 컴포넌트를 추가하여 동적으로 페이지마다 seo를 적용하도록 수정했습니다.
- 로그인 페이지에서 loading을 통해 렌더링을 구분해놓았던 것을 SplashLogin 컴포넌트에 loading을 props로 전달하여 1초 뒤 사라지도록 구현했습니다.

refactor: #193/ seo 컴포넌트 구현

---

src/pages/my/reviews/index.tsx
src/pages/my/titles.tsx
src/pages/shopDetail/index.tsx

close #196 
- 카카오톡 공유 시 서비스 메인 이미지가 나오도록 수정했습니다.
- 내 리뷰 페이지에서 지점명 클릭시 해당 지점 상세 페이지로 이동하도록 수정했습니다.
- 내 칭호 페이지 하단 마진을 추가했습니다.

refactor: #196/ 카카오톡 공유 시 기본 이미지 추가 & 내 리뷰 페이지 지점명 클릭시 지점 상세 페이지로 이동
