4-frame-photos-map/frontend

src/pages/auth/kakao.tsx, src/pages/auth/login.tsx, src/pages/home/index.tsx, src/pages/inquiry.tsx, src/pages/location/index.tsx, src/pages/my/index.tsx, src/pages/my/reviews.tsx, src/pages/my/setting.tsx, src/pages/my/titles.tsx, src/pages/notice.tsx, src/pages/shopDetail/[id].tsx, src/pages/terms.tsx, src/pages/wish/index.tsx
close #6 
- auth/login (로그인)
- auth/kakao (카카오 로그인)
- home (홈)
- location (내주변)
- wish (저장)
- shopDetail (지점 디테일)
- my (마이)
- my/setting (설정)
- my/reviews (내 후기)
- my/titles (내 칭호)
- notice (공지사항)
- inquiry (문의사항)
- terms (약관)
애플리케이션 기본 라우팅을 설정했습니다.
=> feat: #6/라우팅 설정

src/components/common/Layout.tsx, src/components/common/PageLayout.tsx, src/pages/_app.tsx, src/pages/_document.tsx, src/pages/auth/kakao.tsx, src/pages/auth/login.tsx, src/pages/home/index.tsx, src/pages/index.tsx, src/pages/inquiry.tsx, src/pages/location/index.tsx, src/pages/my/index.tsx, src/pages/my/reviews.tsx, src/pages/my/setting.tsx, src/pages/my/titles.tsx, src/pages/notice.tsx, src/pages/shopDetail/[id].tsx, src/pages/terms.tsx, src/pages/wish/index.tsx, tailwind.config.js
close #8 
- 지금 까지 나온 디자인 사항들 tailwind.config 파일에 작성했습니다.
- 공통 레이아웃과 페이지 레이아웃을 작성했습니다.
- _document.tsx 파일내에서 폰트 파일 불러와 전역으로 폰트 설정완료했습니다.
- 모든 라우팅 페이지들 페이지 레이아웃으로 수정했습니다.
스크린샷 또는 GIF를 첨부해주세요.
=> feat: #8/공통 레이아웃 & 페이지 레이아웃 작성

src/components/common/Modal.tsx
=> refactor : #22/ 모달 디자인 수정

src/apis/instance.ts
close #34 
- api 에러 처리 수정에 따라 instance 에러 처리 방법도 수정했습니다.
- 토큰이 없는경우, 유효하지 않은 토큰인 경우 alert 후 로그인 창으로 이동하여 재 로그인 할 수 있게 합니다.
- 만료된 토큰인 경우 refresh토큰으로 재발급 받을 수 있도록 합니다.
=> refactor: #34/ instance 에러처리 수정

src/components/common/Checkbox.tsx, src/components/common/Textarea.tsx, src/pages/my/reviews/edit.tsx
=> refactor: #39/ 리뷰 수정 페이지 디자인 수정사항 반영

src/components/common/Modal.tsx
=> refactor: #54/ 모달 bg 수정

src/components/common/BrandTag.tsx, src/pages/my/setting.tsx
close #56 
- 브랜드태그 컴포넌트에서 undefined 에러가 발생해서 optional chaining 추가하고, 기타 지점 텍스트 컬러 수정했습니다.
- 로그아웃, 회원탈퇴 구현완료했습니다.
https://user-images.githubusercontent.com/79186378/232077201-bac386b1-dc36-44a3-99b1-75d7392fb6eb.mov
=> feat: /#56/로그아웃&회원탈퇴 구현

build.sh
=> feat : build.sh

config.ts, src/apis/instance.ts, src/components/common/Modal.tsx, src/pages/auth/login.tsx
close #65 
- node env의 개발, 배포 환경에 따른 에러처리와, redirect uri를 수정했습니다.
=> feat: #65/node env 구분

src/components/navbar/Search.tsx
모바일 환경에서 input width 가로로 넘치던 현상 해결
- close #67 
- padding 값으로 input 넓이를 조정한 것에서 고정 width 값으로 수정하였습니다.
- 폼 제출 시 아무런 처리를 하지 않도록 수정하였습니다.
=> fix: #67/검색 Input 포지션 수정

src/components/common/Checkbox.tsx
close #69 
- 체크박스를 토글 방식으로 수정했습니다.
=> refactor: #69/checkbox 토글 방식 구현

src/pages/my/edit.tsx
close #78 
- 닉네임 수정시 validation에 따라 에러 메시지를 노출하도록 수정했습니다.
https://user-images.githubusercontent.com/79186378/233586722-7803ae56-9c12-4529-a88c-0e70df4efad2.mov
=> refactor : 닉네임 수정시 validation 메시지 추가

src/@types/index.d.ts, src/components/common/Map.tsx, src/components/common/NavBar.tsx, src/components/navbar/Search.tsx, src/pages/home/index.tsx
close #80 
- 키워드 검색결과를 지도에 마커 표시가 되도록 구현했습니다.
- 마커 클릭시 중앙으로 이동하도록 구현했습니다.
https://user-images.githubusercontent.com/79186378/233764853-86315443-c15c-47d2-958d-9992036c6937.mov
=> feat: #80/ 키워드 검색결과 지도에 마커 표시 구현

next.config.js, src/components/common/Menu.tsx
`/` 경로로 진입 시 `/home`으로 redirect 하도록 설정
- close #88 
- 하단 Menu 바에 아이템들이 중앙 정렬되어있지 않고, 양 요소간의 간격이 처리되지 않아서 이를 수정하였습니다.
=> refactor: #88/Redirect 설정

src/apis/instance.ts
close #93 
- refresh 토큰 관련 에러 핸들링 수정했습니다.
=> refactor: #93/ refresh-token 에러핸들링 수정

src/components/common/NavBar.tsx, src/pages/home/index.tsx, src/pages/location/index.tsx, src/pages/my/edit.tsx, src/pages/my/index.tsx, src/pages/my/reviews/index.tsx, src/pages/my/setting.tsx, src/pages/my/titles.tsx, src/pages/wish/index.tsx
찜 페이지일 때 NavBar 요소 상태 변경
- close #89 
- Area -> leftTitle, title -> centerTitle 로 명칭을 변경했습니다.
=> refactor: #89/찜 페이지 NavBar 요소 상태 변경

src/components/common/NavBar.tsx, src/pages/home/index.tsx
지도지역명 표시
- close #90 
- 재검색 버튼 클릭 시 렌더링 될 때 요소의 위치가 변경돼서 div로 처리하였습니다.
=> feat: #90/지도지역명 표시

src/components/navbar/SearchList.tsx, src/components/navbar/SearchResult.tsx
SearchList & SearchResult 응답값 수정
- resolve #101
=> refactor: #101/SearchList & SearchResult 응답값 수정

src/apis/review/review.d.ts, src/apis/review/reviewApi.ts, src/apis/shop/shop.d.ts, src/components/common/ReviewItem.tsx, src/hooks/mutations/useDeleteReview.ts, src/hooks/mutations/usePatchReview.ts, src/hooks/mutations/usePostReview.ts, src/pages/my/reviews/edit.tsx, src/pages/my/reviews/index.tsx, src/pages/shopDetail/index.tsx, src/pages/shopDetail/review.tsx
close #103 
- 깃북에 반영되어있는 대로 review type을 수정했습니다.
- review type이 수정됨에 따라 관련 페이지와 컴포넌트에서 prop를 수정했습니다.
- 기존에 리뷰 작성, 수정 시 별점만 따로 관리하던 것을, 리뷰 필드 모두 react-hook-form으로 관리하도록 수정했습니다.
=> refactor: #103/ review type 수정 및 리뷰 로직 수정

src/components/common/Scripts.tsx, src/pages/_app.tsx, src/pages/my/reviews/index.tsx, src/pages/shopDetail/index.tsx
close #94 
- 카카오톡 공유 기능을 구현했습니다.
- 기존 카카오 맵에서 참조하는 객체와, 카카오 SDK 에서 참조하는 객체가 달라 추가했습니다.
=> feat: #94/ 카카오톡 공유 구현

src/components/navbar/Search.tsx, src/components/navbar/SearchResult.tsx, src/components/navbar/TextHighlighted.tsx
검색 하이라이팅 버그 수정
- 이 전에 검색어를 입력했을 때 공백이 처리되지 않는 문제를 해결하고 하이라이팅 처리하는 부분을 컴포넌트로 분리했습니다.
- resolve #109
=> fix: #109/검색 하이라이팅 버그 수정

src/pages/my/reviews/index.tsx
close #116 
- 리뷰 수정, 삭제 버튼 수정사항을 반영했습니다.
=> design : #116/ 리뷰 수정,삭제 버튼 수정사항 반영

src/pages/wish/index.tsx
close #115 
- 찜목록 페이지 밑부분이 짤리는 현상을 pb을 추가하여 수정했습니다.
=> design : #115/ 찜목록 페이지 짤림 현상 수정

src/components/wish/WishItem.tsx, src/pages/location/index.tsx
=> fix: #119/찜 삭제 후 토스트 메세지 안 보이는 현상 수정

src/apis/shop/shopApi.ts, src/components/common/LocationMap.tsx, src/components/home/ShopModal.tsx, src/components/location/ShopItem.tsx, src/hooks/queries/useGetShop.ts, src/pages/home/index.tsx, src/pages/location/index.tsx, src/pages/shopDetail/index.tsx
close #121 
- 지점 관련 api 파라미터가 수정됨에 따라 전체적으로 api에 넘겨주는 파라미터를 수정했습니다.
- 내주변 페이지에서는 해당 위치 5km 반경에 해당하는 지점만 나오도록 수정했습니다.
=> refactor: #121/ shop api 변경사항 수정

src/components/common/LocationMap.tsx, src/pages/location/index.tsx
=> refactor: #125/내 주변 결과창만 스크롤 되도록 수정

src/components/navbar/SearchList.tsx, src/components/navbar/SearchResult.tsx, src/components/wish/WishItem.tsx, src/pages/shopDetail/index.tsx
shopDetail로 이동하는 Router.push의 쿼리 파라미터 값을 수정하고 shopDetail에서는 넘겨 받은 쿼리로 useGetShopDetail 파라미터에 전달합니다.
이 전에 반영되었어야 하는 사항이였는데 뒤늦게 캐치했네요..😓
- #132
=> refactor: #132/shopDetail router push 쿼리 파라미터 수정

src/@types/index.d.ts, src/recoil/positionAtom.ts
배포 후 에러 발생으로 undefined 타입 제거
- #139
=> fix: #139/배포 후 에러 발생으로 undefined 타입 제거

src/pages/my/reviews/edit.tsx, src/pages/shopDetail/review.tsx
close #156 
- 리뷰 작성, 수정 페이지에서 콘텐츠가 공백만 있는 경우 버튼을 disabled 처리했습니다.
=> fix : #156/ 리뷰 공백 처리 수정

src/components/common/NavBar.tsx, src/components/common/ShopTitle.tsx, src/components/home/ShopModal.tsx, src/components/location/ShopItem.tsx, src/pages/shopDetail/index.tsx, src/pages/wish/index.tsx
검색 및 찜 총개수 디자인 추가
- close #171
=> design: #171/검색 및 찜 총개수 디자인 추가

src/components/home/Category.tsx, src/components/location/RadiusModal.tsx, src/hooks/queries/useGetShop.ts, src/pages/location/index.tsx, src/styles/globals.css
close #158 
- 내 주변 페이지에서 반경 조절 기능을 추가했습니다.
- 반경 조절 모달 컴포넌트를 구현했습니다.
- 기존에 swiper 구현에서 첫번째 slide의 max-width를 설정하여 구현했던 부분에서, 추가적으로 swiper를 사용하려고 보니 문제가 있어, 모든 swiper slide의 width를 컨텐츠 크기로 수정했습니다.
https://github.com/4-frame-photos-map/frontend/assets/79186378/be8cbc1f-5397-4635-a492-beae9688952b
=> feat: #158/ 내 주변 페이지 반경 조절 기능 추가

src/components/title/TitleModal.tsx, src/pages/my/titles.tsx
획득과 미획득한 칭호에 대한 문구 수정 및 칭호 모달 수정
- close #185 
- 하단 border radius 값 삭제했습니다.
- 칭호 모달 문구를 수정했습니다.
- 칭호 페이지에서 메뉴바를 고려한 하단 마진값 추가했습니다.
=> refactor: #185/획득과 미획득한 칭호에 대한 문구 수정 및 칭호 모달 수정

src/pages/notice.tsx
기존 notice 페이지에서 noticeState타입설정 수정을 안했었네요
한번더 확인부탁드립니다!
=> refactor : noticeState 타입 수정
